/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'slug' : string,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export interface Booking {
  'service' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface ContactSubmission {
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Testimonial {
  'service' : string,
  'review' : string,
  'date' : bigint,
  'name' : string,
  'rating' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'addContactSubmission' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addTestimonial' : ActorMethod<
    [string, string, bigint, string, string],
    undefined
  >,
  'bookConsultation' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getTestimonialsByService' : ActorMethod<[string], Array<Testimonial>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];