/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Booking = IDL.Record({
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'service' : IDL.Text,
  'review' : IDL.Text,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'bookConsultation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getTestimonialsByService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Booking = IDL.Record({
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'service' : IDL.Text,
    'review' : IDL.Text,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'bookConsultation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'getTestimonialsByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };